spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo?serverTimezone=UTC
    username: root
    password: vincentmok2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  redis:
    host: localhost
    port: 6379
server:
  port: 8080
  servlet:
    context-path: /demo

token:
  expires:
    hours: 12

ignored:
  url:
    lists:
      - /api/v1/user/login
      - /api/v1/user/register
