sspring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
  redis:
    host: 192.168.99.100
    port: 6379
server:
  port: 4080

token:
  expires:
    hours: 12

ignored:
  url:
    lists:
      - /api/v1/user/login
      - /api/v1/user/register
